// Automaticaly generated by script/generate_declaration.pl.

#ifndef TEST_DECLARATION_H
#define TEST_DECLARATION_H


static inline void test_tokenizer_main(void);
static inline void test_tokenizer_nfa_engine(void);
void test_main(void);

#endif
