// Automaticaly generated by script/generate_external_declaration.pl.

#ifndef HAVE_DEFINED_EXTERNAL_H_common_
#define HAVE_DEFINED_EXTERNAL_H_common_

extern bool config_grammar_verbose_p(void);
extern bool config_nfa_verbose_p(void);
extern bool config_regular_verbose_p(void);
extern bool config_token_verbose_p(void);
extern bool config_tokenizer_verbose_p(void);
extern char * string_space_skip(char *string);
extern uint32 config_grammar_type(void);
extern void * memory_track_malloc(uint32 size);
extern void * memory_track_realloc(void *ptr, uint32 size);
extern void assert_print_caution(char *msg, const char *fname, const char *func, uint32 line);
extern void assert_print_exit(char *msg, const char *fname, const char *func, uint32 line);
extern void config_initial(void);
extern void memory_track_counters_print(void);
extern void memory_track_free(void *ptr);

#endif

