// Automaticaly generated by script/generate_declaration.pl.

#ifndef HAVE_DEFINED_EXTERNAL_H
#define HAVE_DEFINED_EXTERNAL_H

extern bool nfa_engine_pattern_match_p(s_nfa_t *nfa, char *pn);
extern bool regular_data_p(char c);
extern bool regular_opt_binary_p(char c);
extern bool regular_opt_bracket_left_p(char c);
extern bool regular_opt_bracket_p(char c);
extern bool regular_opt_bracket_right_p(char c);
extern bool regular_opt_p(char c);
extern bool regular_opt_unary_p(char c);
extern char * regular_convert_to_reverse_polish(char *re);
extern s_nfa_t * nfa_engine_create(char *regular);
extern void * memory_track_malloc(uint32 size);
extern void * memory_track_realloc(void *ptr, uint32 size);
extern void assert_print_caution(char *msg, const char *fname, const char *func, uint32 line);
extern void assert_print_exit(char *msg, const char *fname,const char *func, uint32 line);
extern void memory_track_counters_print(void);
extern void memory_track_free(void *ptr);
extern void nfa_engine_destroy(s_nfa_t *nfa);
extern void scil_log_close(void);
extern void scil_log_initial(void);
extern void scil_log_print(const char *format, ...);
extern void test_main(void);

#endif

