// Automaticaly generated by script/generate_declaration.pl.

#ifndef HAVE_DEFINED_EXTERNAL_H
#define HAVE_DEFINED_EXTERNAL_H

extern bool nfa_engine_pattern_match_p(s_nfa_t *nfa, char *pn);
extern s_nfa_t * nfa_engine_create(char *re);
extern void * memory_track_malloc(uint32 size);
extern void assert_print_caution(char *msg, const char *fname, const char *func, uint32 line);
extern void assert_print_exit(char *msg, const char *fname,const char *func, uint32 line);
extern void log_close(void);
extern void log_initial(void);
extern void log_print(const char *format, ...);
extern void memory_track_counters_print(void);
extern void memory_track_free(void *ptr);
extern void nfa_engine_destroy(s_nfa_t *nfa);
extern void test_main(void);

#endif

