// Automaticaly generated by script/generate_external_declaration.pl.

#ifndef HAVE_DEFINED_EXTERNAL_H_log_
#define HAVE_DEFINED_EXTERNAL_H_log_

extern void log_close(void);
extern void log_file_close(void);
extern void log_file_create(char *binary_name);
extern void log_initial(char *logfile_name);
extern void log_print(const char *format, ...);
extern void log_print_and_exit(const char *format, ...);

#endif

