// Automaticaly generated by script/generate_external_declaration.pl.

#ifndef HAVE_DEFINED_EXTERNAL_H_nfa_
#define HAVE_DEFINED_EXTERNAL_H_nfa_

extern bool nfa_engine_pattern_match_p(s_nfa_t *nfa, char *pn);
extern bool nfa_engine_structure_legal_p(s_nfa_t *nfa);
extern s_nfa_t * nfa_engine_create(char *regular);
extern uint32 nfa_engine_token_match(s_nfa_t *nfa, char *pn);
extern void nfa_engine_destroy(s_nfa_t *nfa);

#endif

