// Automaticaly generated by script/generate_external_declaration.pl.

#ifndef HAVE_DEFINED_EXTERNAL_H_regular_
#define HAVE_DEFINED_EXTERNAL_H_regular_

extern bool regular_char_data_p(char c);
extern bool regular_char_meta_p(char c);
extern bool regular_char_translated_p(char c);
extern bool regular_opt_binary_p(char c);
extern bool regular_opt_bracket_left_p(char c);
extern bool regular_opt_bracket_p(char c);
extern bool regular_opt_bracket_right_p(char c);
extern bool regular_opt_p(char c);
extern bool regular_opt_unary_p(char c);
extern char * regular_convert_to_reverse_polish(char *re);
extern char regular_char_translate_resume(char c);

#endif

