// Automaticaly generated by script/generate_external_declaration.pl.

#ifndef HAVE_DEFINED_EXTERNAL_H_test_
#define HAVE_DEFINED_EXTERNAL_H_test_

extern void test_tokenizer_nfa_engine(void);

#endif

