// Automaticaly generated by script/generate_external_declaration.pl.

#ifndef HAVE_DEFINED_EXTERNAL_H_token_
#define HAVE_DEFINED_EXTERNAL_H_token_

extern s_token_language_c_kywd_t * token_language_c_keyword_trie_create(void);
extern void token_language_c_keyword_trie_destroy(s_token_language_c_kywd_t *keyword_trie);

#endif

