// Automaticaly generated by script/generate_external_declaration.pl.

#ifndef HAVE_DEFINED_EXTERNAL_H_tokenizer_
#define HAVE_DEFINED_EXTERNAL_H_tokenizer_

extern bool nfa_engine_pattern_match_p(s_nfa_t *nfa, char *pn);
extern bool regular_char_data_p(char c);
extern bool regular_char_meta_p(char c);
extern bool regular_char_translated_p(char c);
extern bool regular_opt_binary_p(char c);
extern bool regular_opt_bracket_left_p(char c);
extern bool regular_opt_bracket_p(char c);
extern bool regular_opt_bracket_right_p(char c);
extern bool regular_opt_p(char c);
extern bool regular_opt_unary_p(char c);
extern char * regular_convert_to_reverse_polish(char *re);
extern char regular_char_translate_resume(char c);
extern s_nfa_t * nfa_engine_create(char *regular);
extern s_token_file_t * token_file_list_process(char **file_list, uint32 count);
extern s_token_language_c_kywd_t * token_language_c_keyword_trie_create(void);
extern sint32 main(sint32 argc, char **argv);
extern uint32 nfa_engine_token_match(s_nfa_t *nfa, char *pn);
extern void nfa_engine_destroy(s_nfa_t *nfa);
extern void test_main(void);
extern void token_file_list_destroy(s_token_file_t *token_file);
extern void token_language_c_keyword_trie_destroy(s_token_language_c_kywd_t *keyword_trie);

#endif

