// Automaticaly generated by script/generate_declaration.pl.

#ifndef SCIL_DECLARATION_H
#define SCIL_DECLARATION_H


int main(int argc, char **argv);
static inline s_tk_t * scil_tkz_process(char *filename);
static inline void scil_argument_option_process(char *option);
static inline void scil_argument_process(uint32 argc, char **argv);
static inline void scil_process_i(char *filename);

#endif
