#!/usr/bin/perl
use strict;
use warnings;
use 5.010;

if ($#ARGV < 1) {
    say "ARGV format:";
    say "    perl $0 <external header file name> <module list>.";
    die "Unknown ARGV";
}

my $extern = shift @ARGV;
my @extern_list;
my $module = "_";

foreach (@ARGV) {
   my $entry = $_;

   &module_external_scan($entry);
   $module = $module . "$1" . "_" if $entry =~ /(\w+)\/?$/;
}

&external_declaration_generate();

sub module_external_scan () {
    my $module = shift @_;

    unless (-e -d $module) {
        &file_external_scan($module);
    } else {
        opendir my $dir, $module or
           die "Failed to opendir $module, $!";
        my @file_list = readdir($dir);

        foreach my $entry (@file_list) {
            chomp $entry;
            next if $entry =~ /\.h$/;
            next if $entry =~ /^\.$/;
            next if $entry =~ /^\.\.$/;
            next if $entry =~ /[Mm]akefile/;

            my $full_path = "$module/$entry";
            &module_external_scan($full_path);
        }

        closedir($dir);
    }
}

sub file_external_scan() {
    my $filename = shift @_;
    my $is_decl = "false";
    my $decl = "extern";
    my $real;

    open FILE, '<', $filename or
       die "Failed to open $filename, $!";

    while (<FILE>) {
        if (/^{$/ or /\/\*/) {
            $is_decl = "true";
            next;
        } elsif (/^}$/ or /\*\//) {
            $is_decl = "false";
            next;
        }
        next if /#include/ or /^$/ or /^#/ or /\/\//;
        next if $is_decl eq "true";

        chomp;
        $real = $_;
        $real = $1 if /^\s+(.*)/;
        $decl = "$decl $real";

        if (/\)$/) {
            push @extern_list, "$decl;" unless $decl =~ /static/;
            $decl = "extern";
        }
    }

    close FILE;
}

sub external_declaration_generate() {
    my @sorted = sort @extern_list;
    my $extern_file = $extern;

    open EXT, '>', $extern_file or
       die "Failed to open $extern_file, $!";

    print EXT "// Automaticaly generated by $0.\n\n";
    print EXT "#ifndef HAVE_DEFINED_EXTERNAL_H$module\n";
    print EXT "#define HAVE_DEFINED_EXTERNAL_H$module\n\n";

    foreach (@sorted) {
        print EXT "$_\n";
    }

    print EXT "\n#endif\n\n";

    close EXT;
}

