#!/usr/bin/perl
use strict;
use warnings;
use 5.010;

my $out_dir = shift @ARGV;

if (not $out_dir) {
    say "Invalid option for script.";
    exit 1;
}

my $binary_dir = "$out_dir/../bin";
my $obj_list = "";

foreach (split /\n/, `ls $out_dir/*.o`) {
    $obj_list = join(' ', $obj_list, $1) if /\/(\w+\.o)$/;
}

$obj_list = join(' ', $obj_list, "libds.a");

&produce_link_makefile();

sub produce_link_makefile {
    my $makefile;
    my $makefile_name;

    $makefile_name = "$out_dir/Makefile";

    open $makefile, '>', "$makefile_name" or
        die "Failed to create makefile, $?\n";

    printf $makefile "# Automaticaly generated by $0.\n\n";
    printf $makefile "include Makefile.in\n\n";
    printf $makefile "TARGET=scil.elf\n\n";
    printf $makefile 'all:$(TARGET)' ."\n\n";
    printf $makefile '$(TARGET):' . "$obj_list\n";
    printf $makefile "\t" . '$(LD) $(LFLAG) -o $@ $? $(LD_LIBRARY)' . "\n";
    printf $makefile "\t" . "cp \$(TARGET) $binary_dir" . "\n\n";

    close $makefile;
}

