#!/usr/bin/perl
use strict;
use 5.010;

my $output = shift @ARGV;
my $binary_dir = "$output/../bin";
my @obj_list = "";

die "Failed to find output directory, $output." unless -d -e $output;

##############################################
## Collecting all objective files in output ##
##############################################
opendir OUTPUT, $output or
    die "Failed to open output directory $output, $?\n";

while(readdir(OUTPUT)) {
    unshift @obj_list, $_ if /\w+\.o$/;
    push @obj_list, $_ if /\w+\.a$/;
}

closedir OUTPUT;

######################################
## Generate link Makefile in output ##
######################################
open MAKEFILE, '>', "$output/Makefile" or
    die "Failed to create makefile, $?\n";

printf MAKEFILE "# Automaticaly generated by $0.\n\n";
printf MAKEFILE "include Makefile.in\n\n";
printf MAKEFILE "TKZ=tokenizer.elf\n\n";
printf MAKEFILE 'all:$(TKZ)' ."\n\n";
printf MAKEFILE '$(TKZ):' . "@obj_list\n";
printf MAKEFILE "\t" . '$(LD) $(LFLAG) -o $@ $? $(LD_LIBRARY)' . "\n";
printf MAKEFILE "\t" . "cp \$(TKZ) $binary_dir" . "\n\n";

close MAKEFILE;

