// Automaticaly generated by script/generate_declaration.pl.

#ifndef LOG_DECLARATION_H
#define LOG_DECLARATION_H

void log_close(void);
void log_file_close(void);
void log_file_create(char *binary_name);
void log_initial(char *logfile_name);
void log_print(const char *format, ...);
void log_print_and_exit(const char *format, ...);

#endif
