// Automaticaly generated by script/generate_declaration.pl.

#ifndef LOG_DECLARATION_H
#define LOG_DECLARATION_H

void scil_log_close(void);
void scil_log_initial(void);
void scil_log_print(const char *format, ...);

#endif
